# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 23:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180131_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='unique_date',
            field=models.DateField(default=datetime.datetime(2018, 1, 31, 23, 34, 37, 553892, tzinfo=utc)),
        ),
    ]
